### ISSUE TITLE
Dimensionsmodellering

### ISSUE THREAD

**Issue by Rajneetsami** [KristoferFangrat/Team_engineer#9]
Bygga på dimensionsmodellering så att dimensionsmodellen ska förbättras

**Comment by jasse-f** [comment]
Jag och kristoffer har gjort ett db-diagram som kan användas till en början för vår nya modell i warehouse.
Kristoffer jobbar på att skriva den i draw.io, vi skrev på tavlan men tog bilder.

**Comment by KristoferFangrat** [comment]
Welldone.
